<a href="https://colab.research.google.com/github/zeze1004/Introduction_Data_Analysis/blob/main/numpy%EC%99%80_%EC%84%A0%ED%98%95%EB%8C%80%EC%88%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 영벡터
np.zeros(2)

array([0., 0.])

In [ ]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# 1벡터
np.ones((3,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [ ]:
# 대각행렬
# 대각선을 제외한 성분이 0인 행렬
np.diag((2,4))

array([[2, 0],
       [0, 4]])

In [ ]:
# 항등행렬 = 대각행렬 원소가 모두 1인 행렬
# 대각선이 1인 대각행렬
np.eye(2,dtype=int) # type 디폴트는 float

array([[1, 0],
       [0, 1]])

In [ ]:
np.eye(2,dtype=complex) # complex는 복소수(i, python에서는 j로 표시)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [ ]:
# 행렬곱
# np.dot() or @ 사용

mat_1 = np.array([[1,4],[2,3]])
mat_2 = np.array([[7,9],[0,6]])

mat_1.dot(mat_2)
mat_1 @ mat_2

array([[ 7, 33],
       [14, 36]])

In [ ]:
# 트레이스: 매트릭스의 대각선의 합
# np.trace()

arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.trace() # 1+ 5 + 9

15

In [ ]:
np.eye(2).trace()

2.0

In [ ]:
# 행렬식: 행렬을 대표하는 값들 중 하나
# 행렬식이 0이면 역행렬이 존재하지 않음
# np.linalg.det() 

np.linalg.det(arr)
# np.array([[1,2,3],[4,5,6],[7,8,9]])를 역행렬 함수(np.linalg.inv())에 넣으면 에러 남

0.0

In [ ]:
arr2 = np.array([[1,4,7],[2,5,8],[3,6,9]])
np.linalg.det(arr2) # arr1을 뒤집은 형태

0.0

A = 
$$\left[\begin{array}{rrr} 
a&b\\
d&d
\end{array}\right]$$
 =


In [ ]:
# 역행렬
# 자기자신과 자기자신의 역행렬 곱하면 항등행렬이 나온다

arr = np.array([[1,4],[2,3]])
arr

array([[1, 4],
       [2, 3]])

In [ ]:
arr_inv = np.linalg.inv(arr)
arr_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [ ]:
arr1 = np.array([[2,0,1],[-2,3,4],[-5,5,6]])
arr1

array([[ 2,  0,  1],
       [-2,  3,  4],
       [-5,  5,  6]])

In [ ]:
value = np.linalg.inv(arr1)
value

array([[ -2.,   5.,  -3.],
       [ -8.,  17., -10.],
       [  5., -10.,   6.]])

In [ ]:
# 역행렬 확인
eye = arr @ arr_lnv
eye


array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00]])

## 과제
1. 어떤 백터가 주어졌을 때 L2 norm을 구하는 함수 get_L2_norm() 작성해라.

In [ ]:
vector = np.random.randint(1,10, size=5)
vector

array([2, 1, 2, 8, 1])

In [ ]:
def get_L2_norm(vector):
  L2_norm = np.linalg.norm(vector)
  print(L2_norm)

get_L2_norm(vector)


8.602325267042627


2. 어떤 행렬이 singular matrix인지 확인하는 함수 is_singular() 작성하시오.

- 매개변수: 2차원 백터(np.array)
- return: 인자로 주어진 벡터가 singular하면 true, non-singualr하면 false로 반환

In [ ]:
vector = np.random.randint(1,10, size=(2,2))
vector

array([[9, 8],
       [3, 4]])

In [ ]:
def is_singular(vector):
  if np.linalg.det(vector) == 0:
    print("is_singular")
    return Ture 
  else:
    print("none_singular")
    return False

is_singular(vector)

none_singular


False